# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "cloud-profile-sync"
SPDX-PackageDownloadLocation = "https://github.com/cobaltcore-dev/cloud-profile-sync"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "**/zz_generated.deepcopy.go",
  "crd/*",
]
SPDX-FileCopyrightText = "2020 The Kubernetes Authors"
SPDX-License-Identifier = "Apache-2.0"
