//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfile) DeepCopyInto(out *ManagedCloudProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfile.
func (in *ManagedCloudProfile) DeepCopy() *ManagedCloudProfile {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCloudProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileList) DeepCopyInto(out *ManagedCloudProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedCloudProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileList.
func (in *ManagedCloudProfileList) DeepCopy() *ManagedCloudProfileList {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCloudProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileMachineImages) DeepCopyInto(out *ManagedCloudProfileMachineImages) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Provider.DeepCopyInto(&out.Provider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileMachineImages.
func (in *ManagedCloudProfileMachineImages) DeepCopy() *ManagedCloudProfileMachineImages {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileMachineImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileMachineImagesProvider) DeepCopyInto(out *ManagedCloudProfileMachineImagesProvider) {
	*out = *in
	if in.IroncoreMetal != nil {
		in, out := &in.IroncoreMetal, &out.IroncoreMetal
		*out = new(ManagedCloudProfileMachineImagesProviderIroncoreMetal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileMachineImagesProvider.
func (in *ManagedCloudProfileMachineImagesProvider) DeepCopy() *ManagedCloudProfileMachineImagesProvider {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileMachineImagesProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileMachineImagesProviderIroncoreMetal) DeepCopyInto(out *ManagedCloudProfileMachineImagesProviderIroncoreMetal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileMachineImagesProviderIroncoreMetal.
func (in *ManagedCloudProfileMachineImagesProviderIroncoreMetal) DeepCopy() *ManagedCloudProfileMachineImagesProviderIroncoreMetal {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileMachineImagesProviderIroncoreMetal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileMachineImagesSource) DeepCopyInto(out *ManagedCloudProfileMachineImagesSource) {
	*out = *in
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(ManagedCloudProfileMachineImagesSourceOCI)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileMachineImagesSource.
func (in *ManagedCloudProfileMachineImagesSource) DeepCopy() *ManagedCloudProfileMachineImagesSource {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileMachineImagesSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileMachineImagesSourceOCI) DeepCopyInto(out *ManagedCloudProfileMachineImagesSourceOCI) {
	*out = *in
	out.Password = in.Password
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileMachineImagesSourceOCI.
func (in *ManagedCloudProfileMachineImagesSourceOCI) DeepCopy() *ManagedCloudProfileMachineImagesSourceOCI {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileMachineImagesSourceOCI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileSpec) DeepCopyInto(out *ManagedCloudProfileSpec) {
	*out = *in
	in.CloudProfile.DeepCopyInto(&out.CloudProfile)
	if in.MachineImages != nil {
		in, out := &in.MachineImages, &out.MachineImages
		*out = new(ManagedCloudProfileMachineImages)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileSpec.
func (in *ManagedCloudProfileSpec) DeepCopy() *ManagedCloudProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileStatus) DeepCopyInto(out *ManagedCloudProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileStatus.
func (in *ManagedCloudProfileStatus) DeepCopy() *ManagedCloudProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
