//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/gardener/gardener/pkg/apis/core/v1beta1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProfileSpec) DeepCopyInto(out *CloudProfileSpec) {
	*out = *in
	if in.CABundle != nil {
		in, out := &in.CABundle, &out.CABundle
		*out = new(string)
		**out = **in
	}
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	if in.MachineImages != nil {
		in, out := &in.MachineImages, &out.MachineImages
		*out = make([]v1beta1.MachineImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MachineTypes != nil {
		in, out := &in.MachineTypes, &out.MachineTypes
		*out = make([]v1beta1.MachineType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]v1beta1.Region, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SeedSelector != nil {
		in, out := &in.SeedSelector, &out.SeedSelector
		*out = new(v1beta1.SeedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeTypes != nil {
		in, out := &in.VolumeTypes, &out.VolumeTypes
		*out = make([]v1beta1.VolumeType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bastion != nil {
		in, out := &in.Bastion, &out.Bastion
		*out = new(v1beta1.Bastion)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(v1beta1.Limits)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineCapabilities != nil {
		in, out := &in.MachineCapabilities, &out.MachineCapabilities
		*out = make([]v1beta1.CapabilityDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProfileSpec.
func (in *CloudProfileSpec) DeepCopy() *CloudProfileSpec {
	if in == nil {
		return nil
	}
	out := new(CloudProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineImageUpdate) DeepCopyInto(out *MachineImageUpdate) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Provider.DeepCopyInto(&out.Provider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineImageUpdate.
func (in *MachineImageUpdate) DeepCopy() *MachineImageUpdate {
	if in == nil {
		return nil
	}
	out := new(MachineImageUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineImageUpdateProvider) DeepCopyInto(out *MachineImageUpdateProvider) {
	*out = *in
	if in.IroncoreMetal != nil {
		in, out := &in.IroncoreMetal, &out.IroncoreMetal
		*out = new(MachineImagesUpdateProviderIroncoreMetal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineImageUpdateProvider.
func (in *MachineImageUpdateProvider) DeepCopy() *MachineImageUpdateProvider {
	if in == nil {
		return nil
	}
	out := new(MachineImageUpdateProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineImageUpdateSource) DeepCopyInto(out *MachineImageUpdateSource) {
	*out = *in
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(MachineImageUpdateSourceOCI)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineImageUpdateSource.
func (in *MachineImageUpdateSource) DeepCopy() *MachineImageUpdateSource {
	if in == nil {
		return nil
	}
	out := new(MachineImageUpdateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineImageUpdateSourceOCI) DeepCopyInto(out *MachineImageUpdateSourceOCI) {
	*out = *in
	out.Password = in.Password
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineImageUpdateSourceOCI.
func (in *MachineImageUpdateSourceOCI) DeepCopy() *MachineImageUpdateSourceOCI {
	if in == nil {
		return nil
	}
	out := new(MachineImageUpdateSourceOCI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineImagesUpdateProviderIroncoreMetal) DeepCopyInto(out *MachineImagesUpdateProviderIroncoreMetal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineImagesUpdateProviderIroncoreMetal.
func (in *MachineImagesUpdateProviderIroncoreMetal) DeepCopy() *MachineImagesUpdateProviderIroncoreMetal {
	if in == nil {
		return nil
	}
	out := new(MachineImagesUpdateProviderIroncoreMetal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfile) DeepCopyInto(out *ManagedCloudProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfile.
func (in *ManagedCloudProfile) DeepCopy() *ManagedCloudProfile {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCloudProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileList) DeepCopyInto(out *ManagedCloudProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedCloudProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileList.
func (in *ManagedCloudProfileList) DeepCopy() *ManagedCloudProfileList {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCloudProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileSpec) DeepCopyInto(out *ManagedCloudProfileSpec) {
	*out = *in
	in.CloudProfile.DeepCopyInto(&out.CloudProfile)
	if in.MachineImageUpdates != nil {
		in, out := &in.MachineImageUpdates, &out.MachineImageUpdates
		*out = make([]MachineImageUpdate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileSpec.
func (in *ManagedCloudProfileSpec) DeepCopy() *ManagedCloudProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCloudProfileStatus) DeepCopyInto(out *ManagedCloudProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCloudProfileStatus.
func (in *ManagedCloudProfileStatus) DeepCopy() *ManagedCloudProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedCloudProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
